

### TURN RIGHT (1a - right)

PUT http://localhost:8080/timelapse/execute
Content-Type: application/json

{
  "robots": {
    "EV3": {
      "wheelDiameter": 4.8,
      "trackWidth": 14,
      "leftMotor": "B",
      "rightMotor": "C",
      "angularSpeed": 5.5125,
      "linearSpeed": 1.25,
      "linearAcceleration": 50
    }
  },
  "cameras": {
  },
  "keyFrames": [
    {
      "robotName": "EV3",
      "point": {
        "x": 0,
        "y": 0
      },
      "direction": {
        "x": 0,
        "y": 1
      }
    },
    {
      "robotName": "EV3",
      "point": {
        "x": 40,
        "y": 20
      },
      "direction": {
        "x": 1,
        "y": 0
      }
    }
  ]
}

### TURN RIGHT (1b - left)

PUT http://localhost:8080/timelapse/execute
Content-Type: application/json

{
  "robots": {
    "EV3": {
      "wheelDiameter": 4.8,
      "trackWidth": 14,
      "leftMotor": "B",
      "rightMotor": "C",
      "angularSpeed": 5.5125,
      "linearSpeed": 1.25,
      "linearAcceleration": 50
    }
  },
  "cameras": {
  },
  "keyFrames": [
    {
      "robotName": "EV3",
      "point": {
        "x": 0,
        "y": 0
      },
      "direction": {
        "x": 0,
        "y": 1
      }
    },
    {
      "robotName": "EV3",
      "point": {
        "x": -40,
        "y": 20
      },
      "direction": {
        "x": 1,
        "y": 0
      }
    }
  ]
}

### TURN RIGHT (2)

PUT http://localhost:8080/timelapse/execute
Content-Type: application/json

{
  "robots": {
    "EV3": {
      "wheelDiameter": 4.8,
      "trackWidth": 14,
      "leftMotor": "B",
      "rightMotor": "C",
      "angularSpeed": 5.5125,
      "linearSpeed": 1.25,
      "linearAcceleration": 50
    }
  },
  "cameras": {
  },
  "keyFrames": [
    {
      "robotName": "EV3",
      "point": {
        "x": 0,
        "y": 0
      },
      "direction": {
        "x": 0,
        "y": 1
      }
    },
    {
      "robotName": "EV3",
      "point": {
        "x": 40,
        "y": 20
      },
      "direction": {
        "x": 1,
        "y": 0
      }
    }
  ]
}