# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.1.0.RELEASE/multi/multi__actuator_api.html

PUT http://localhost:8080/robots/registrations/EV3
Accept: application/json

###

DELETE http://localhost:8080/robots/registrations/EV3
Accept: application/json

###

PUT http://localhost:8080/robots/EV3/pilots/main
Content-Type: application/json

{
  "wheelDiameter": 4.32,
  "trackWidth": 10,
  "leftMotor": "B",
  "rightMotor": "C"
}

###

PUT http://localhost:8080/robots/EV3/pilots/main/arc
Content-Type: application/json

{
  "radius": 20,
  "angle": 180
}

###

PUT http://localhost:8080/robots/EV3/pilots/main/forward
Content-Type: application/json

{
  "distance": 20
}

###

PUT http://localhost:8080/robots/EV3/pilots/main/rotate
Content-Type: application/json

{
  "angle": -360
}

###